[package]
name = "gedcomx"
version = "0.1.1"
authors = ["Ephraim Kunz <ephraimkunz@me.com>"]
edition = "2018"
description = "The core data structures and serialization / deserialization of the GEDCOM X format."
keywords = ["genealogy", "gedcomx", "family-trees"]
categories = ["encoding", "parsing"]
license = "MIT"
repository = "https://github.com/ephraimkunz/gedcomx-rs/tree/main/gedcomx"
readme = "README.md"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_with = "1"
chrono = { version = "0.4", features = ["serde"] }
thiserror = "1"
yaserde = "0.7"
yaserde_derive = "0.7"
gedcomx_date = "0.0.2"
serde_json = "1"

[dev-dependencies]
pretty_assertions = "0.7"
assert-json-diff = "2"
env_logger = "0.8"