[package]
name = "gedcomx"
version = "0.1.0"
authors = ["Ephraim Kunz <ephraimkunz@me.com>"]
edition = "2018"
description = "A library for working with GEDCOMX"
keywords = ["genealogy", "gedcomx", "family-trees"]
categories = ["encoding", "parsing"]
license = "MIT"
repository = "https://github.com/ephraimkunz/gedcomx-rs"
readme = "README.md"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_with = "1"
chrono = { version = "0.4", features = ["serde"] }
thiserror = "1"
yaserde = {git = "https://github.com/ephraimkunz/yaserde.git", branch = "gedcomx-fixes"}
yaserde_derive = {git = "https://github.com/ephraimkunz/yaserde.git", branch = "gedcomx-fixes"}
log = "0.4"
xml-rs = "0.8"
gedcomx_date = {git = "https://github.com/ephraimkunz/gedcomx-date-rs.git", branch = "fix-duration"}

[dev-dependencies]
pretty_assertions = "0.6"
assert-json-diff = "2"
serde_json = "1"
env_logger = "0.8"